version: '2'

services:
   db:
     image: mysql:5.7
     ports:
     - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: root-pw
       MYSQL_DATABASE: bank
       MYSQL_USER: user
       MYSQL_PASSWORD: pass